# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0003_mymodel_year_in_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='customer_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Sevnior')], default='FR', max_length=2),
        ),
    ]
