# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0008_auto_20160306_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='inviter',
        ),
    ]
