# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0010_auto_20160309_0632'),
    ]

    operations = [
    ]
