# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0014_auto_20160420_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='cities',
            new_name='city',
        ),
    ]
