# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0015_auto_20160420_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cities',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='countries',
            new_name='Country',
        ),
    ]
